name: Monitor Metro CDMX

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '5 0-6,11-23 * * *'

jobs:
  vigilancia-metro:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librer√≠as
        run: |
          python -m pip install --upgrade pip
          # Eliminamos Pillow, dejamos solo lo esencial para datos
          pip install requests ntscraper feedparser pytz beautifulsoup4 fake-useragent

      - name: Ejecutar Monitor
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: python main.py
