name: Monitor Metro CDMX

on:
  # 1. AUTO-TEST AL GUARDAR CAMBIOS
  push:
    branches:
      - main
      
  # 2. BOTÓN MANUAL (Para pruebas instantáneas)
  workflow_dispatch:

  # 3. HORARIO DE SERVICIO (Una vez cada hora)
  # Ejecución al minuto :05 de cada hora.
  # El rango 11-23 y 0-6 en UTC cubre de las 5:05 AM a las 12:05 AM hora CDMX.
  schedule:
    - cron: '5 0-6,11-23 * * *'

jobs:
  vigilancia-metro:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: |
          python -m pip install --upgrade pip
          # AGREGADO: beautifulsoup4 para el Modo Espía
          pip install requests ntscraper feedparser pytz beautifulsoup4

      - name: Ejecutar Monitor
        env:
          # --- CREDENCIALES ---
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          
          # --- DESTINOS (Dual Broadcast) ---
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}       # Grupo Privado
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }} # Canal Público (NUEVO)
          
        run: python main.py
